on:
  push:
    branches: [ "master" ]
  release:
    types: [ "published" ]

name: Publish Docker Image

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Build the Docker image using Nix
        run: nix build -L -f. turbocheck-image --no-link

      - name: Load the image into Docker
        run: docker load -i "$(nix path-info -L -f. turbocheck-image)"

      - name: Create a temporary Dockerfile
        run: echo "FROM turbocheck:$(nix eval -f. --raw turbocheck-image.imageTag)" > Dockerfile

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: cpcloud/turbocheck
          tag_with_ref: true
          tag_with_sha: true
