on:
  push:
    branches: [ "master" ]

name: Publish Docker Image

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Build the Docker image using Nix
        run: |
          nix build -f. turbocheck-image
          docker load -i ./result
